# Generated by Django 3.1.2 on 2020-12-01 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('fecha_emision', models.DateField()),
                ('cliente_nombre', models.CharField(max_length=30)),
                ('cliente_direccion', models.CharField(max_length=50)),
                ('cliente_telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ref_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=30)),
                ('descripcion_producto', models.CharField(blank=True, max_length=250, null=True)),
                ('precio_unitario', models.IntegerField()),
                ('seccion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LineaFactura',
            fields=[
                ('id_linea', models.AutoField(primary_key=True, serialize=False)),
                ('unidades', models.IntegerField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='factura.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='factura.producto')),
            ],
        ),
    ]
